### ISSUE TITLE
NameError: name 'SCAN_SUBNETS' is not defined

### ISSUE THREAD

**Issue by p1r473** [pucherot/Pi.Alert#112]
Hi all,
Does anyone know what could cause this?
```
root@Harbormaster:~# python3 /home/linaro/pialert/back/pialert.py 1

Pi.Alert 3.01 (2021-04-22)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2021-04-24 00:19:00

Scanning...
    arp-scan Method...
Traceback (most recent call last):
  File "/home/linaro/pialert/back/pialert.py", line 1486, in <module>
    sys.exit(main())
  File "/home/linaro/pialert/back/pialert.py", line 85, in main
    res = scan_network()
  File "/home/linaro/pialert/back/pialert.py", line 361, in scan_network
    arpscan_devices = execute_arpscan (arpscan_retries)
  File "/home/linaro/pialert/back/pialert.py", line 451, in execute_arpscan
    subnets = SCAN_SUBNETS.strip().split()
NameError: name 'SCAN_SUBNETS' is not defined
```

**Comment by p1r473** [comment]
This error was from me backing up an OLD version of pialert.conf which didnt have SCAN_SUBNETS at the bottom, like the latest version does.

**Comment by pucherot** [comment]
Update script don't overwrite `pialert.conf` and adds the new entries (like `SCAN_SUBNETS`).
In the future use update script.
