### ISSUE TITLE
Option to disable STARTTLS missing

### ISSUE THREAD

**Issue by dado991** [pucherot/Pi.Alert#115]
Hi,
i'm using a local SMTP Relay without encryption and user login.

```
Reporting...
    Formating report...
    Sending report by email...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())
  File "/home/pi/pialert/back/pialert.py", line 94, in main
    email_reporting()
  File "/home/pi/pialert/back/pialert.py", line 1324, in email_reporting
    send_email (mail_text, mail_html)
  File "/home/pi/pialert/back/pialert.py", line 1416, in send_email
    smtp_connection.starttls()
  File "/usr/lib/python3.7/smtplib.py", line 752, in starttls
    "STARTTLS extension not supported by server.")
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.
```

Is there a way to disable login and STARTTLS encryption for SMTP configuration?

Thank You!

**Comment by dado991** [comment]
If it can be useful, commenting out these lines inside _back\pialert.py_ the emails arrive correctly.
It would be wonderful to be able to set this behavior in the configuration file 

```
def send_email (pText, pHTML):
    # Compose email
    msg = MIMEMultipart('alternative')
    msg['Subject'] = 'Pi.Alert Report'
    msg['From'] = REPORT_FROM
    msg['To'] = REPORT_TO
    msg.attach (MIMEText (pText, 'plain'))
    msg.attach (MIMEText (pHTML, 'html'))

    # Send mail
    smtp_connection = smtplib.SMTP (SMTP_SERVER, SMTP_PORT)
#    smtp_connection.ehlo()
#    smtp_connection.starttls()
    smtp_connection.ehlo()
#    smtp_connection.login (SMTP_USER, SMTP_PASS)
    smtp_connection.sendmail (REPORT_FROM, REPORT_TO, msg.as_string())
    smtp_connection.quit()
```

**Comment by pucherot** [comment]
Thank you
I'll include a new option in the configuration file.

**Comment by dado991** [comment]
You are welcome 😁

**Comment by Thijn** [comment]
While you're at it, could you also enable the option to not specify user and password?
I have a SMTP server running on the host I'm running Pi.Alert on, so it can relay mail without authentication.

This worked for me, keeping SMTP_USER and SMTP_PASS as empty strings in my config:
```python
    # Send mail
    smtp_connection = smtplib.SMTP (SMTP_SERVER, SMTP_PORT)
    smtp_connection.ehlo()
    smtp_connection.starttls()
    smtp_connection.ehlo()

    if SMTP_USER != "" :
        smtp_connection.login (SMTP_USER, SMTP_PASS)

    smtp_connection.sendmail (REPORT_FROM, REPORT_TO, msg.as_string())
    smtp_connection.quit()```
