### ISSUE TITLE
Help, pi.alert does not open the Pihole database.

### ISSUE THREAD

**Issue by don-teka** [pucherot/Pi.Alert#120]
I managed to make Pi.Alert work with Pihole, but it has an error when scanning the network, it can't open the database file, I don't know if it's due to its size, about 250MB. I leave the Pi.Alert log below.

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2021-05-01 20:20:00

Scanning...
    arp-scan Method...
    Pi-hole Method...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 85, in main
    res = scan_network()
  File "/home/pi/pialert/back/pialert.py", line 370, in scan_network
    copy_pihole_network()
  File "/home/pi/pialert/back/pialert.py", line 505, in copy_pihole_network
    sql.execute ("ATTACH DATABASE '"+ PIHOLE_DB +"' AS PH")
sqlite3.OperationalError: unable to open database: /etc/pihole/pihole-FTL.db

**Comment by don-teka** [comment]
Problem solved, I changed path of Pi-hole in config file of pi.alert.
