### ISSUE TITLE
Vendors update script do not work

### ISSUE THREAD

**Issue by qawsed55** [pucherot/Pi.Alert#137]
I have try to install PiAlert and this error was present.
Then I tried to manually update vendors and that was in console:

```
######################################################################### 100.0%
######################################################################### 100.0%
######################################################################### 100.0%
Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/arm-linux-gnueabihf/perl5/5.30 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/sbin/get-iab line 36.
BEGIN failed--compilation aborted at /usr/sbin/get-iab line 36.
Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/arm-linux-gnueabihf/perl5/5.30 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/sbin/get-oui line 31.
BEGIN failed--compilation aborted at /usr/sbin/get-oui line 31.
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())
  File "/root/pialert/back/pialert.py", line 81, in main
    res = update_devices_MAC_vendors()
  File "/root/pialert/back/pialert.py", line 264, in update_devices_MAC_vendors
    update_output = subprocess.check_output (update_args)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sh', '/root/pialert/back/update_vendors.sh', '']' returned non-zero exit status 2.
```

**Comment by qawsed55** [comment]
`apt-get install libwww-perl`
and all done!

**Comment by ogghi** [comment]
Not working here, despite libwww-perl being installed...?
