### ISSUE TITLE
Pi.Alert update script issue

### ISSUE THREAD

**Issue by WildWeasel109** [pucherot/Pi.Alert#157]
Hi again,

When I run the update script (paler_update.sh) I get the following error (also got it on install) stating there was an issue with the vendor update script. I fixed the update script to download the correct files (using -L) and can run vendor_update.sh with no errors being generated.

Any idea on how to fix the update script?

Error msg generated by pialert_update.sh:
Updating vendors DB (iab & oui)...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())       
  File "/root/pialert/back/pialert.py", line 83, in main
    res = update_devices_MAC_vendors('-s')
  File "/root/pialert/back/pialert.py", line 264, in update_devices_MAC_vendors
    update_output = subprocess.check_output (update_args)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sh', '/root/pialert/back/update_vendors.sh', '-s']' returned non-zero exit status 255.

Output from update_vendors script (with -L fix):
root@Pi2:~/pialert/back# ./update_vendors.sh
Updating... /usr/share/ieee-data/
######################################################################################################################################################################################################### 100.0%

Updating... /usr/share/arp-scan/
Fetching IAB data from file://var/lib/ieee-data/iab.txt
Fetched 2453481 bytes
Opening output file ieee-iab.txt
4575 IAB entries written to file ieee-iab.txt
Fetching OUI data from file://var/lib/ieee-data/oui.txt
Fetched 5144489 bytes
Opening output file ieee-oui.txt
31984 OUI entries written to file ieee-oui.txt

**Comment by cengbrecht** [comment]
There is a pull request pending here:
[https://github.com/pucherot/Pi.Alert/pull/166](https://github.com/pucherot/Pi.Alert/pull/166)
This should solve the issue if that particular merge relating to the https issues is accepted.
This fix replaces the http's in the update script with https.
