### ISSUE TITLE
Can not update - vendors files empty...

### ISSUE THREAD

**Issue by AubreyKloppers** [pucherot/Pi.Alert#164]
Good morning
When I try to update the following error gets displayed and the vendor files are empty...

```
Updating vendors DB (iab & oui)...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())       
  File "/root/pialert/back/pialert.py", line 83, in main
    res = update_devices_MAC_vendors('-s')
  File "/root/pialert/back/pialert.py", line 264, in update_devices_MAC_vendors
    update_output = subprocess.check_output (update_args)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sh', '/root/pialert/back/update_vendors.sh', '-s']' returned non-zero exit status 255.
```

**Comment by AubreyKloppers** [comment]
When I change the "update_vendors.sh" script to use wget it works:

`echo Updating... /usr/share/ieee-data/
cd /usr/share/ieee-data/

sudo mkdir -p 2_backup
#sudo cp *.txt 2_backup
mv *.txt 2_backup
#sudo cp *.csv 2_backup
mv *.csv 2_backup

# sudo curl $1 -# -O http://standards-oui.ieee.org/iab/iab.csv
wget http://standards-oui.ieee.org/iab/iab.csv
# sudo curl $1 -# -O http://standards-oui.ieee.org/iab/iab.txt
wget http://standards-oui.ieee.org/iab/iab.txt

# sudo curl $1 -# -O http://standards-oui.ieee.org/oui28/mam.csv
wget http://standards-oui.ieee.org/oui28/mam.csv
# sudo curl $1 -# -O http://standards-oui.ieee.org/oui28/mam.txt
wget http://standards-oui.ieee.org/oui28/mam.txt

# sudo curl $1 -# -O http://standards-oui.ieee.org/oui36/oui36.csv
wget http://standards-oui.ieee.org/oui36/oui36.csv
# sudo curl $1 -# -O http://standards-oui.ieee.org/oui36/oui36.txt
wget http://standards-oui.ieee.org/oui36/oui36.txt

# sudo curl $1 -# -O http://standards-oui.ieee.org/oui/oui.csv
wget http://standards-oui.ieee.org/oui/oui.csv
# sudo curl $1 -# -O http://standards-oui.ieee.org/oui/oui.txt
wget http://standards-oui.ieee.org/oui/oui.txt

`

**Comment by AubreyKloppers** [comment]
Found resove by another ticket.  Please close/delete...

**Comment by cengbrecht** [comment]
There is a pull request pending here:
[https://github.com/pucherot/Pi.Alert/pull/166](https://github.com/pucherot/Pi.Alert/pull/166)
This should solve the issue if that particular merge relating to the https issues is accepted.
