### ISSUE TITLE
Pi.Alert cant update Vendors

### ISSUE THREAD

**Issue by missbella90** [pucherot/Pi.Alert#165]
Hey i just installed Pi.Alert and while installing I got the error that it cant update HW Vendors

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2022-05-19 11:52:00

Updating vendors DB (iab & oui)...
Traceback (most recent call last):
  File "/home/pihole/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())
  File "/home/pihole/pialert/back/pialert.py", line 83, in main
    res = update_devices_MAC_vendors('-s')
  File "/home/pihole/pialert/back/pialert.py", line 264, in update_devices_MAC_vendors
    update_output = subprocess.check_output (update_args)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sh', '/home/pihole/pialert/back/update_vendors.sh', '-s']' returned non-zero exit status 255.

- Testing Pi.Alert Internet IP Lookup...

**Comment by leiweibau** [comment]
Check the files "pialert/back/update_vendors.sh". The lines 27-37 contain URLs like "http://standards-oui.ieee.org/iab/iab.csv". Change all of the "http" to "https". Then everything should be fine.

**Comment by cengbrecht** [comment]
Confirmed this fix does indeed make the update work.

**Comment by cengbrecht** [comment]
There is a pull request pending here:
[https://github.com/pucherot/Pi.Alert/pull/166](https://github.com/pucherot/Pi.Alert/pull/166)
This should solve the issue if that particular merge relating to the https issues is accepted.

**Comment by leiweibau** [comment]
I'm sorry, but my pull request is not related to this issue.

**Comment by missbella90** [comment]
okay I'll do that

**Comment by leiweibau** [comment]
I've opened a specific pull request that addresses this issue [#167](https://github.com/pucherot/Pi.Alert/pull/167)

**Comment by missbella90** [comment]
okay i did what was recommended and it worked.
Fixed it for me and the vendors are correctly displayed too

and if it gets fixed in a later build thats okay then

**Comment by SMarx94** [comment]
For the future, you can also use the -L argument for curl to support redirects.

E.g.: `sudo curl $1 -# -L -O http://standards-oui.ieee.org/iab/iab.csv`

**Comment by grumpazoid** [comment]
I have edited pialert/back/update_vendors.sh as suggested. How do I now force an update?

**Comment by SMarx94** [comment]
@grumpazoid Just run `bash update_vendors.sh` or `./update_vendors.sh` and wait for the update process to be finished
