### ISSUE TITLE
ERROR on E-Mail Report

### ISSUE THREAD

**Issue by theniwo** [pucherot/Pi.Alert#17]
My Config:
```
SMTP_SERVER     = 'smtp.gmail.com'
SMTP_PORT       = 587
SMTP_USER       = 'root.niwo@gmail.com'
SMTP_PASS       = 'XXX'

REPORT_MAIL     = True
REPORT_FROM     = 'Pi.Alert <' + SMTP_USER +'>'
REPORT_TO       = 'root.niwo@gmail.com'
```

The Error:

```
[...]
Reporting...
    Formating report...
    Sending report by email...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1336, in <module>
    sys.exit(main())
  File "/home/pi/pialert/back/pialert.py", line 84, in main
    email_reporting()
  File "/home/pi/pialert/back/pialert.py", line 1172, in email_reporting
    send_email (mail_text, mail_html)
  File "/home/pi/pialert/back/pialert.py", line 1262, in send_email
    smtp_connection = smtplib.SMTP (SMTP_SERVER, SMTP_PORT)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 317, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 292, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 99] Cannot assign requested address
```
python --version
Python 2.7.16

**Comment by theniwo** [comment]
No, but my lighttpd is configured to listen to port 8080.
I reach pialert via pi4:8080/pialert.

**Comment by theniwo** [comment]
Looks like i just had the firewall blocking port 587. The error message was a bit misleading. 
Solved!

**Comment by pucherot** [comment]
Perfect. Thank you four your comment.
I'll add more info in the error message.
