### ISSUE TITLE
Network scan 1 and 15 is not working via crontab

### ISSUE THREAD

**Issue by marosrr** [pucherot/Pi.Alert#170]
Hello all,

coul someone please help me?
When i run /pialert.py 1 or 15 manually everything is working fine, but when it should run via crontab i see follwing error in logs:

Scanning...
    arp-scan Method...
Traceback (most recent call last):
  File "/home/myadmin/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())
  File "/home/myadmin/pialert/back/pialert.py", line 85, in main
    res = scan_network()
  File "/home/myadmin/pialert/back/pialert.py", line 361, in scan_network
    arpscan_devices = execute_arpscan (arpscan_retries)
  File "/home/myadmin/pialert/back/pialert.py", line 463, in execute_arpscan
    arpscan_output = subprocess.check_output (arpscan_args, universal_newlines=True)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'arp-scan', '--ignoredups', '--retry=16', '--localnet']' returned non-zero exit status 1.

pialert.py internet_IP is working fine also pialert.py update_vendors

Thank you for help

**Comment by jzawacki** [comment]
Not the best advice, but if you run the uninstall script under the myadmin account, sudo to root, and then run the installer, that fixed it for me (installs and runs as root, which isn't a great idea).  If you manually run the command in crontab for myadmin, you will see it is asking for your sudo password.
