### ISSUE TITLE
Webhook error

### ISSUE THREAD

**Issue by berkobob** [pucherot/Pi.Alert#200]
I edited my config file to use a slack webhook but I'm getting the following log report:

```
Reporting...
    Formating report...
    Skip mail...
    Skip Apprise...
    Sending report by webhook...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1811, in <module>
    sys.exit(main())
  File "/home/pi/pialert/back/pialert.py", line 107, in main
    email_reporting()
  File "/home/pi/pialert/back/pialert.py", line 1450, in email_reporting
    send_webhook (json_final, mail_text)
  File "/home/pi/pialert/back/pialert.py", line 1634, in send_webhook
    curlParams = ["curl","-i","-X", "GET" ,"-H", "Content-Type:application/json" ,"-d", json.dumps(_json_payload), _WEBHOOK_URL]
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**Comment by leiweibau** [comment]
As far as I know, the webhook is only used in @jokob-sk's fork. Probably no one here will be able to handle it. I recommend you to close the issue here and open it in the fork of @jokob-sk
