### ISSUE TITLE
Not finding any devices

### ISSUE THREAD

**Issue by jstraten** [pucherot/Pi.Alert#204]
My Pi Alert is not finding any devices. What could be the problem?

Thanks!

**Comment by leiweibau** [comment]
Open a console/terminal and run the scan manually

`python ~/pialert/back/pialert.py 1`

**Comment by jstraten** [comment]
Thank you for getting back to me!

I am getting the following output:

python3 ~/pialert/back/pialert.py 1

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Scan Devices
ScanCycle: 1
Timestamp: 2022-10-29 19:13:00
Traceback (most recent call last):
File "/home/user/pialert/back/pialert.py", line 1488, in <module>
sys.exit(main())
File "/home/user/pialert/back/pialert.py", line 85, in main
res = scan_network()
File "/home/user/pialert/back/pialert.py", line 344, in scan_network
scanCycle_data = query_ScanCycle_Data (True)
File "/home/user/pialert/back/pialert.py", line 431, in query_ScanCycle_Data
openDB()
File "/home/user/pialert/back/pialert.py", line 1438, in openDB
sql_connection = sqlite3.connect (DB_PATH, isolation_level=None)
sqlite3.OperationalError: unable to open database file

Weird, the installation went smooth.

How can I fix it? Thanks!

**Comment by leiweibau** [comment]
Please check https://github.com/leiweibau/Pi.Alert/issues/33#issuecomment-1291503664

**Comment by leiweibau** [comment]
If the folder "~/pialert/db" should be empty, I would recommend a reinstallation of Pi.Alert. Maybe this will fix your problem.
