### ISSUE TITLE
Scan Results cannot be saved in Database

### ISSUE THREAD

**Issue by Arragon5xpwm** [pucherot/Pi.Alert#211]
```
Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Scan Devices
    ScanCycle: 15
    Timestamp: 2023-02-02 10:14:00

Scanning...
    arp-scan Method...
    Pi-hole Method...
    DHCP Leases Method...

Processing scan results...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())
  File "/home/pi/pialert/back/pialert.py", line 85, in main
    res = scan_network()
  File "/home/pi/pialert/back/pialert.py", line 379, in scan_network
    save_scanned_devices (arpscan_devices, cycle_interval)
  File "/home/pi/pialert/back/pialert.py", line 568, in save_scanned_devices
    sql.execute ("""INSERT INTO CurrentScan (cur_ScanCycle, cur_MAC,
sqlite3.IntegrityError: NOT NULL constraint failed: CurrentScan.cur_IP
```

**Comment by leiweibau** [comment]
Hello,

I would guess Pi.Alert is not able to determine your Internet IP.

Also, I would recommend you to use one of the actively developed forks of Pi.Alert, as this main project has not been maintained for almost 2 years.

**Comment by Arragon5xpwm** [comment]
`python3 ~/pialert/back/pialert.py internet_IP` shows my correct IP.
I just installed it using the script.  Which fork is recommended?

**Comment by leiweibau** [comment]
> `python3 ~/pialert/back/pialert.py internet_IP` shows my correct IP.
> I just installed it using the script. Which fork is recommended?

That is strange.

Here you have an overview of the forks of Pi.Alert. 
https://techgaun.github.io/active-forks/index.html#pucherot/pi.alert

**Comment by Arragon5xpwm** [comment]
Thanks
