### ISSUE TITLE
No emails - smtplib.SMTPServerDisconnected: Connection unexpectedly closed

### ISSUE THREAD

**Issue by Backfire-FF** [pucherot/Pi.Alert#227]
I just installed Pi.Alert and run the update and got the message below:

```
Reporting...
    Formating report...
    Sending report by email...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())       
  File "/root/pialert/back/pialert.py", line 94, in main
    email_reporting()
  File "/root/pialert/back/pialert.py", line 1324, in email_reporting
    send_email (mail_text, mail_html)
  File "/root/pialert/back/pialert.py", line 1414, in send_email
    smtp_connection = smtplib.SMTP (SMTP_SERVER, SMTP_PORT)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 343, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python3.10/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
```

What could be the problem? Any advice?
Thanks

**Comment by jokob-sk** [comment]
> If you want to have things fixed or get help, you should switch to one of the forks. The main project has not been maintained for almost 2 years.
> For example:
> https://github.com/leiweibau/Pi.Alert
> https://github.com/jokob-sk/Pi.Alert
