### ISSUE TITLE
Update script errors

### ISSUE THREAD

**Issue by BCS64-IT** [pucherot/Pi.Alert#230]
Running PI.Alert on a virtual Debian server hosting PI-Hole ( latest version )
executing: curl -sSL https://github.com/pucherot/Pi.Alert/raw/main/install/pialert_update.sh | bash

results in : 
`Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Update HW Vendors
    Timestamp: 2023-05-25 05:44:00

Updating vendors DB (iab & oui)...
Traceback (most recent call last):
  File "/root/pialert/back/pialert.py", line 1488, in <module>
    sys.exit(main())
  File "/root/pialert/back/pialert.py", line 83, in main
    res = update_devices_MAC_vendors('-s')
  File "/root/pialert/back/pialert.py", line 264, in update_devices_MAC_vendors
    update_output = subprocess.check_output (update_args)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sh', '/root/pialert/back/update_vendors.sh', '-s']' returned non-zero exit status 255.

- Testing Pi.Alert Internet IP Lookup...

Pi.Alert 3.02 (2021-04-24)
---------------------------------------------------------
Check Internet IP
    Timestamp: 2023-05-25 05:44:00

Retrieving Internet IP...
    XXX.146.XXX.XXX

Retrieving previous IP...
    XXX.146.XXX.XXX
    No changes to perform

Skipping Dynamic DNS update...

DONE!!!

- Testing Pi.Alert Network scan...
*** PLEASE WAIT A COUPLE OF MINUTES...
WARNING: Cannot open MAC/Vendor file /usr/share/arp-scan/ieee-oui.txt: No such file or directory
WARNING: Cannot open MAC/Vendor file /usr/share/arp-scan/ieee-iab.txt: No such file or directory
grep: /usr/share/arp-scan/ieee-oui.txt: No such file or directory
grep: /usr/share/arp-scan/ieee-oui.txt: No such file or directory
grep: /usr/share/arp-scan/ieee-oui.txt: No such file or directory
grep: /usr/share/arp-scan/ieee-oui.txt: No such file or directory
grep: /usr/share/arp-scan/ieee-oui.txt: No such file or directory

Pi.Alert 3.02 (2021-04-24)`

**Comment by leiweibau** [comment]
If you are already using the latest version, why do you run the update script? There is no new version for over 2 years? As long as you don't use one of the maintained forks (which have their own update scripts), you won't need the updatescript. If you want to have support, you should also switch to the actively maintained forks.
