### ISSUE TITLE
No entries under Devices Link / Dashboard

### ISSUE THREAD

**Issue by FuXXz** [pucherot/Pi.Alert#251]
Hello everyone,
My Devices Tab does not show any devices. At the top it says xx My Devices, XX connected, xx new devices.
Everything seems to be ok, under network I see all devices, I can click on them, assign them, 

edit etc.
Only the first link with Devices shows nothing.
In the Web Console of the Broser I see
Uncaught TypeError: Cannot read properties of null (reading 'trim')
    at Object.<anonymous> (devices.php:1035:38)
    at Function.each (jquery.min.js:2:2777)
    at getNumberOfChildren (devices.php:1033:5)
    at devices.php:816:17
    at Array.map (<anonymous>)
    at Object.success (devices.php:798:28)
    at c (jquery.min.js:2:27742)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28487)
    at l (jquery.min.js:2:78789)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:81117)
![Screenshot 2024-02-16 103436](https://github.com/pucherot/Pi.Alert/assets/9010594/64610014-8516-46f3-b87b-28b471e32fba)

Enviroment:
Docker on Synology Raid
Docker on Unraid, both show the same issues

**Comment by jokob-sk** [comment]
Hi there, please close this issue as it's not opened on the correct fork. See info here: https://github.com/pucherot/Pi.Alert/issues/235

The reported issue has been reported and fixed here: https://github.com/jokob-sk/Pi.Alert/issues/568
